### ISSUE TITLE
Add CODEOWNERS file

### ISSUE THREAD

**Issue by AlexAxthelm** [RMI-PACTA/actions#36]
I'm thinking that the CODEOWNERS for this repo (who would be tagged on all PRs) should maybe be @RMI-PACTA/developers, but maybe we want to have that on README (which should be updated for all new workflows), but specify individuals for certain files (for example, any non-breaking changes to the `docker-*` workflows are probably of interest to a few of us, but not everyone)

**Comment by jdhoffa** [comment]
I tend to think now that just you @AlexAxthelm should maintain this? You will be submitting most PRs. And you can just request a review from whoever you think it would affect on any contentious PR.

but you seem to have most context here by a long shot.

**Comment by AlexAxthelm** [comment]
I'm thinking that's the right call for most of the files, but I think I'd like to keep @RMI-PACTA/r-developers` on the `R.yml` file, and `@RMI-PACTA/devops` on the docker.yml file, and `@RMI-PACTA/developers` on the other "calling" workflows (`general.yml`, housekeeping, `issue.yml`, etc) Since those may change default behaviors if anyone is using the `@main` branch

**Comment by AlexAxthelm** [comment]
Closed in #73
