### ISSUE TITLE
remove testing with R v3.6

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/actions#88]
r-lib's examples/check-full.yaml no longer supports R v3.6
https://github.com/r-lib/actions/commit/30cc889da92691a41efe29876fe70d797039033d

so we will likely need to stop supporting it also, e.g.

here
https://github.com/RMI-PACTA/actions/blob/3f33e65349a9f6817462f186dc2389e48ceec33b/.github/workflows/R-CMD-check.yml#L20

and here
https://github.com/RMI-PACTA/actions/blob/3f33e65349a9f6817462f186dc2389e48ceec33b/.github/workflows/R.yml#L51

**Comment by AlexAxthelm** [comment]
@RMI-PACTA/r-developers I'm inclined to remove Windows+R 3.6 from our testing matrix, unless anyone has a compelling reason that we should keep it in.
